# Generated by Django 5.2.11 on 2026-02-05 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_client_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('booking_date', models.DateField(verbose_name='Дата занятия')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('room', models.CharField(default='Зал 1', max_length=50, verbose_name='Зал')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='main.clients', verbose_name='Клиент')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='main.services', verbose_name='Услуга')),
                ('trainer', models.ForeignKey(blank=True, db_column='trainer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.trainers', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Запись на занятие',
                'verbose_name_plural': 'Записи на занятия',
                'db_table': 'Bookings',
                'ordering': ['booking_date', 'start_time'],
            },
        ),
    ]
