# Generated by Django 5.2.11 on 2026-02-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.CharField(choices=[('hall1', 'Зал 1: Силовые тренировки'), ('hall2', 'Зал 2: Кардио тренировки'), ('hall3', 'Зал 3: Игровые развлечения'), ('pool', 'Бассейн: Аквааэробика')], default='hall1', max_length=50, verbose_name='Зал'),
        ),
    ]
